version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tododb_sql
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  app:
    build: .
    container_name: todoapp
    depends_on:
      - sqlserver
    ports:
      - "5000:80"
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=tododb;User Id=sa;Password=YourStrong!Passw0rd;"
